// examples/expo/src/components/ConnectionBadge/ConnectionBadge.tsx
import type React from "react";
import { formatConnectionState, getConnectionTone } from "example-shared";
import { CircleNotch, Plugs, PlugsConnected } from "phosphor-react-native";
import { useConnectionState } from "@priemskiyyy/simulcast-react";
import { match } from "ts-pattern";
import { Badge } from "src/components/Badge/Badge";

export const ConnectionBadge: React.FunctionComponent = () => {
  const connection = useConnectionState();
  const icon = match(connection)
    .with("connected", () => PlugsConnected)
    .with("connecting", () => CircleNotch)
    .with("disconnected", () => Plugs)
    .exhaustive();

  return (
    <Badge tone={getConnectionTone(connection)} icon={icon}>
      {formatConnectionState(connection)}
    </Badge>
  );
};

// examples/svelte/src/components/ConnectionBadge.svelte
<script lang="ts">
  import { formatConnectionState, getConnectionTone } from "example-shared";
  import { CircleNotch, Plugs, PlugsConnected } from "phosphor-svelte";
  import { useConnectionState } from "@priemskiyyy/simulcast-svelte";
  import { match } from "ts-pattern";
  import Badge from "src/components/Badge.svelte";

  const connection = useConnectionState();
  const icon = $derived(
    match(connection.current)
      .with("connected", () => PlugsConnected)
      .with("connecting", () => CircleNotch)
      .with("disconnected", () => Plugs)
      .exhaustive(),
  );
</script>

<Badge tone={getConnectionTone(connection.current)} {icon}>
  {formatConnectionState(connection.current)}
</Badge>
