// examples/vue/src/components/ConnectionBadge.vue
<script setup lang="ts">
import { PhCircleNotch, PhPlugs, PhPlugsConnected } from "@phosphor-icons/vue";
import { formatConnectionState, getConnectionTone } from "example-shared";
import { useConnectionState } from "@priemskiyyy/simulcast-vue";
import { match } from "ts-pattern";
import { computed } from "vue";
import Badge from "src/components/Badge.vue";

const connection = useConnectionState();
const icon = computed(() =>
  match(connection.value)
    .with("connected", () => PhPlugsConnected)
    .with("connecting", () => PhCircleNotch)
    .with("disconnected", () => PhPlugs)
    .exhaustive(),
);
</script>

<template>
  <Badge :tone="getConnectionTone(connection)" :icon="icon">
    {{ formatConnectionState(connection) }}
  </Badge>
</template>

// examples/react/src/components/ConnectionBadge/ConnectionBadge.tsx
import type React from "react";
import { CircleNotch, Plugs, PlugsConnected } from "@phosphor-icons/react";
import { formatConnectionState, getConnectionTone } from "example-shared";
import { useConnectionState } from "@priemskiyyy/simulcast-react";
import { match } from "ts-pattern";
import { Badge } from "src/components/Badge/Badge";

export const ConnectionBadge: React.FunctionComponent = () => {
  const connection = useConnectionState();
  const icon = match(connection)
    .with("connected", () => PlugsConnected)
    .with("connecting", () => CircleNotch)
    .with("disconnected", () => Plugs)
    .exhaustive();

  return (
    <Badge tone={getConnectionTone(connection)} icon={icon}>
      {formatConnectionState(connection)}
    </Badge>
  );
};
