// examples/vue/src/Application.vue
<script setup lang="ts">
import {
  initialApplicationState,
  createRealtimeClient,
  resolveSource,
} from "example-shared";
import { SimulcastDevtools } from "@priemskiyyy/simulcast-devtools/vue";
import { RealtimeProvider } from "@priemskiyyy/simulcast-vue";
import { computed, reactive } from "vue";
import Dashboard from "src/components/Dashboard.vue";
import Header from "src/components/Header.vue";
import SimulationControls from "src/components/SimulationControls.vue";

const state = reactive({ ...initialApplicationState });
// The adapter captures its endpoint, so the client changes exactly when the source does.
const isDevelopment = import.meta.env.DEV;
const client = computed(() =>
  createRealtimeClient(
    resolveSource({ sourceType: state.sourceType, endpoint: state.endpoint }),
  ),
);
</script>

<template>
  <RealtimeProvider :client="client" :session="{ enabled: state.enabled }">
    <Header
      v-model:source-type="state.sourceType"
      v-model:endpoint="state.endpoint"
      v-model:room-id="state.roomId"
      :enabled="state.enabled"
      @session-toggle="state.enabled = !state.enabled"
    />
    <main class="mx-auto flex max-w-6xl flex-col gap-6 px-6 py-8">
      <SimulationControls
        v-if="state.sourceType === 'SIMULATION'"
        :room-id="state.roomId"
      />
      <Dashboard :key="state.roomId" :room-id="state.roomId" />
    </main>
    <SimulcastDevtools v-if="isDevelopment" />
  </RealtimeProvider>
</template>

// examples/react/src/Application.tsx
import type React from "react";
import {
  applicationReducer,
  createRealtimeClient,
  initialApplicationState,
  resolveSource,
} from "example-shared";
import { useMemo, useReducer } from "react";
import { SimulcastDevtools } from "@priemskiyyy/simulcast-devtools/react";
import { RealtimeProvider } from "@priemskiyyy/simulcast-react";
import { Dashboard } from "src/components/Dashboard/Dashboard";
import { Header } from "src/components/Header/Header";
import { SimulationControls } from "src/components/SimulationControls/SimulationControls";
import "src/styles.css";

export const Application: React.FunctionComponent = () => {
  const [state, dispatch] = useReducer(
    applicationReducer,
    initialApplicationState,
  );
  const { sourceType, endpoint } = state;
  // The adapter captures its endpoint, so the client changes exactly when the source does.
  const client = useMemo(
    () => createRealtimeClient(resolveSource({ sourceType, endpoint })),
    [sourceType, endpoint],
  );

  return (
    <RealtimeProvider client={client} session={{ enabled: state.enabled }}>
      <Header
        state={state}
        onSourceSelect={(sourceType) =>
          dispatch({ type: "SOURCE_SELECTED", sourceType })
        }
        onEndpointChange={(endpoint) =>
          dispatch({ type: "ENDPOINT_CHANGED", endpoint })
        }
        onRoomChange={(roomId) => dispatch({ type: "ROOM_CHANGED", roomId })}
        onSessionToggle={() => dispatch({ type: "SESSION_TOGGLED" })}
      />
      <main className="mx-auto flex max-w-6xl flex-col gap-6 px-6 py-8">
        {state.sourceType === "SIMULATION" ? (
          <SimulationControls roomId={state.roomId} />
        ) : null}
        <Dashboard key={state.roomId} roomId={state.roomId} />
      </main>
      {import.meta.env.DEV ? <SimulcastDevtools /> : null}
    </RealtimeProvider>
  );
};
