// packages/solid/src/components/RealtimeProvider.ts
import {
  createComponent,
  createEffect,
  createMemo,
  on,
  onCleanup,
} from "solid-js";
import type { Component, ParentProps } from "solid-js";
import type { RealtimeClient } from "@priemskiyyy/simulcast";
import { RealtimeClientContext } from "src/context/RealtimeClientContext";

export type RealtimeProviderProps = ParentProps<{
  client: RealtimeClient;
  session?: {
    /** Identifies the session, usually the signed-in account. Changing it replaces the connection. */
    id?: string;
    /** Whether a session should be active. Defaults to true. */
    enabled?: boolean;
  };
}>;

/**
 * Owns the client's session while mounted. Changing the session ID or disabling
 * it releases the previous connection; primitives keep their registrations.
 * Effects do not run on the server, so server rendering opens nothing.
 *
 * @example
 * ```tsx
 * <RealtimeProvider client={realtime} session={{ id: user().id }}>
 *   <Room />
 * </RealtimeProvider>
 * ```
 */
export const RealtimeProvider: Component<RealtimeProviderProps> = (props) => {
  const session = () => props.session ?? {};
  const client = createMemo(() => props.client);
  // Memos compare by value, so a new session object with the same ID does not reconnect.
  const id = createMemo(() => session().id);
  const enabled = createMemo(() => session().enabled ?? true);

  createEffect(
    on([client, id, enabled], ([current, , active]) => {
      if (!active) {
        return;
      }

      onCleanup(current.connect());
    }),
  );

  return createComponent(RealtimeClientContext.Provider, {
    value: client,
    get children() {
      return props.children;
    },
  });
};

// packages/react/src/context/RealtimeProvider.tsx
import { useEffect } from "react";
import type { PropsWithChildren } from "react";
import type { RealtimeClient } from "@priemskiyyy/simulcast";
import { RealtimeClientContext } from "src/context/RealtimeClientContext";

export type RealtimeProviderProps = PropsWithChildren<{
  client: RealtimeClient;
  session?: {
    /** Identifies the session, usually the signed-in account. Changing it replaces the connection. */
    id?: string;
    /** Whether a session should be active. Defaults to true. */
    enabled?: boolean;
  };
}>;

/**
 * Owns the client's session while mounted. Changing the session ID or disabling
 * it releases the previous connection; hooks keep their registrations.
 *
 * @example
 * ```tsx
 * const realtime = new RealtimeClient({ adapter: centrifugo({ transport }) });
 *
 * <RealtimeProvider client={realtime} session={{ id: user.id }}>
 *   <div>Connected components go here.</div>
 * </RealtimeProvider>
 * ```
 */
export const RealtimeProvider = ({
  client,
  session = {},
  children,
}: RealtimeProviderProps) => {
  const { id, enabled = true } = session;

  useEffect(() => {
    if (!enabled) {
      return;
    }

    return client.connect();
  }, [client, id, enabled]);

  return (
    <RealtimeClientContext.Provider value={client}>
      {children}
    </RealtimeClientContext.Provider>
  );
};
