// packages/svelte/src/components/RealtimeProvider.svelte
<!--
@component
Owns the client's session while mounted. Changing the session ID or disabling
it releases the previous connection; utilities keep their registrations.
Effects do not run on the server, so server rendering opens nothing.

@example
```svelte
<RealtimeProvider client={realtime} session={{ id: user.id }}>
  <Room />
</RealtimeProvider>
```
-->
<script lang="ts">
  import { setRealtimeClient } from "../context/realtimeClientContext.js";
  import type { RealtimeProviderProps } from "../types/RealtimeProviderProps.js";

  const props: RealtimeProviderProps = $props();

  // Deriveds only change by value, so a new session object with the same ID is
  // inert. The ID is part of the active value so that changing it reconnects.
  const client = $derived(props.client);
  const id = $derived(props.session?.id);
  const enabled = $derived(props.session?.enabled ?? true);
  const active = $derived(enabled ? { client, id } : null);

  setRealtimeClient({
    get current() {
      return client;
    },
  });

  $effect(() => {
    if (active === null) {
      return;
    }

    return active.client.connect();
  });
</script>

{#if props.children}
  {@render props.children()}
{/if}

// packages/solid/src/components/RealtimeProvider.ts
import {
  createComponent,
  createEffect,
  createMemo,
  on,
  onCleanup,
} from "solid-js";
import type { Component, ParentProps } from "solid-js";
import { RealtimeClientContext } from "src/context/RealtimeClientContext";
import type { RegisteredClient } from "src/types/Register";

export type RealtimeProviderProps = ParentProps<{
  client: RegisteredClient;
  session?: {
    /** Identifies the session, usually the signed-in account. Changing it replaces the connection. */
    id?: string;
    /** Whether a session should be active. Defaults to true. */
    enabled?: boolean;
  };
}>;

/**
 * Owns the client's session while mounted. Changing the session ID or disabling
 * it releases the previous connection; primitives keep their registrations.
 * Effects do not run on the server, so server rendering opens nothing.
 *
 * @example
 * ```tsx
 * <RealtimeProvider client={realtime} session={{ id: user().id }}>
 *   <Room />
 * </RealtimeProvider>
 * ```
 */
export const RealtimeProvider: Component<RealtimeProviderProps> = (props) => {
  const session = () => props.session ?? {};
  const client = createMemo(() => props.client);
  // Memos compare by value, so a new session object with the same ID does not reconnect.
  const id = createMemo(() => session().id);
  const enabled = createMemo(() => session().enabled ?? true);

  createEffect(
    on([client, id, enabled], ([current, , active]) => {
      if (!active) {
        return;
      }

      onCleanup(current.connect());
    }),
  );

  return createComponent(RealtimeClientContext.Provider, {
    value: client,
    get children() {
      return props.children;
    },
  });
};
