// examples/expo/src/components/ConnectionBadge/ConnectionBadge.tsx
import type React from "react";
import { formatConnectionState, getConnectionTone } from "example-shared";
import { CircleNotch, Plugs, PlugsConnected } from "phosphor-react-native";
import { useConnectionState } from "@priemskiyyy/simulcast-react";
import { match } from "ts-pattern";
import { Badge } from "src/components/Badge/Badge";

export const ConnectionBadge: React.FunctionComponent = () => {
  const connection = useConnectionState();
  const icon = match(connection)
    .with("connected", () => PlugsConnected)
    .with("connecting", () => CircleNotch)
    .with("disconnected", () => Plugs)
    .exhaustive();

  return (
    <Badge tone={getConnectionTone(connection)} icon={icon}>
      {formatConnectionState(connection)}
    </Badge>
  );
};

// examples/solid/src/components/ConnectionBadge/ConnectionBadge.tsx
import type { Component } from "solid-js";
import { formatConnectionState, getConnectionTone } from "example-shared";
import { LoaderCircle, Plug, PlugZap } from "lucide-solid";
import { useConnectionState } from "@priemskiyyy/simulcast-solid";
import { match } from "ts-pattern";
import { Badge } from "src/components/Badge/Badge";

export const ConnectionBadge: Component = () => {
  const connection = useConnectionState();
  const icon = () =>
    match(connection())
      .with("connected", () => PlugZap)
      .with("connecting", () => LoaderCircle)
      .with("disconnected", () => Plug)
      .exhaustive();

  return (
    <Badge tone={getConnectionTone(connection())} icon={icon()}>
      {formatConnectionState(connection())}
    </Badge>
  );
};
