// packages/solid/src/primitives/useChannelStatus.ts
import { createMemo } from "solid-js";
import { useObservableValue } from "src/primitives/internal/useObservableValue";
import { useRealtimeClient } from "src/primitives/useRealtimeClient";
import type { ChannelInput } from "src/types/ChannelInput";
import { access } from "src/utils/internal/access";

/**
 * Observes channel status as an accessor without opening a native subscription.
 * Reads `detached` until a publication consumer opens one.
 *
 * @example
 * ```ts
 * const status = useChannelStatus(() => `rooms:${roomId()}`);
 * ```
 */
export const useChannelStatus = (channel: ChannelInput) => {
  const client = useRealtimeClient();
  const name = createMemo(() => access(channel));

  return useObservableValue(() => client().channel(name()).status);
};

// packages/react/src/hooks/useChannelStatus.ts
import { useMemo } from "react";
import { DETACHED_CHANNEL_STATUS } from "simulcast";
import type { ChannelStatus } from "simulcast";
import { useObservableValue } from "src/hooks/internal/useObservableValue";
import { useRealtimeClient } from "src/hooks/useRealtimeClient";

const getServerChannelStatus = () => DETACHED_CHANNEL_STATUS;

/**
 * Observes channel status without opening a native subscription.
 * Returns `detached` until a publication consumer opens one; `onChange` runs on subsequent updates.
 *
 * @example
 * ```ts
 * const { state, error } = useChannelStatus("rooms:general", (status) => {
 *   console.log("Channel:", status.state);
 * });
 * ```
 */
export const useChannelStatus = (
  channel: string,
  onChange?: (status: ChannelStatus) => void | Promise<unknown>,
) => {
  const client = useRealtimeClient();

  // Channel handles are created on demand; keep the subscription stable across renders.
  const status = useMemo(
    () => client.channel(channel).status,
    [client, channel],
  );

  return useObservableValue(status, getServerChannelStatus, onChange);
};
